---
title: "AUPEC work"
author: "Jack Deschler"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Functions and setup from prior document
```{r}
# libraries and setup
library(evalITR)
library(dplyr)
library(haven)

# read data
df <- read_dta("~/Desktop/HKS/G1 Fall/Gov 2003/Final Paper/Replication package/Field experiment data and code/TextMessageData.dta")

# subset to only those with the newform?
df <- df[df$NewForm == 1,]

# Create Treatment column (original does not work for some reason)
df$Treatment <- df$consequences + df$planmaking + df$combination

# Flip FTA because a success is actually appearing
df$success <- 1 - df$FTA


control <- df[df$Treatment == 0,]
treated_overall <- df[df$Treatment == 1,]
cons <- df[df$consequences == 1,]
plan <- df[df$planmaking == 1,]
combo <- df[df$combination == 1,]

pape_matrix <- function(d, itr_cols = c('itr_plan', 'itr_cons', 'itr_combo')) {
  itr_treat <- as.numeric(d$itr_plan + d$itr_cons + d$itr_combo > 0)
  appeared <- 1 - d$FTA

  names <- list("Any Text", "Planmaking", "Consequences", "Combination")
  orig <- data.frame(d$Treatment, d$planmaking, d$consequences, d$combination)
  itr <- data.frame(itr_treat, d[itr_cols[1]], d[itr_cols[2]], d[itr_cols[3]])
  pape_mat <- matrix(nrow = 4, ncol = 4, c(names, names))
  sd_mat <- matrix(nrow = 4, ncol = 4, c(names, names))
  for (r in 1:length(names)) {
    for (c in 1:length(names)) {
      p = PAPE(orig[,r], itr[,c], appeared, centered = FALSE)
      pape_mat[r,c] <- p$pape
      sd_mat[r,c] <- p$sd
    }
  }
  rownames(pape_mat) <- names
  colnames(pape_mat) <- names
  rownames(sd_mat) <- names
  colnames(sd_mat) <- names
  return(tibble(pape = pape_mat, sd = sd_mat))
}

pape_matrix_to_metric <- function(papes, weights) {
  if(!is.matrix(weights)) {
    weights <- diag(weights)
  }
  return(papes %*% weights)
}
```

# AUPEC calculations - have to bootstrap
```{r eval = F}
binary_itrs <- read.csv('Desktop/HKS/G1 Fall/Gov 2003/Final Paper/text-itr/binary_itrs.csv')
forest100results <- read.csv('Desktop/HKS/G1 Fall/Gov 2003/Final Paper/text-itr/binary_100trees_results.csv')

colnames(tmp) <- c("treat", "tau", "appeared")
bootstrapfunc <- function(tmp) {
  colnames(tmp) <- c("treat", "tau", "appeared")
  resamp <- tmp[sample(nrow(tmp), 10000, replace = TRUE),]
  return(AUPEC(resamp$treat, resamp$tau, resamp$appeared))
}

# Best Performing Cross-Validated forests
strict <- read.csv('cv_output/strict_defendant_100.csv')
simple <- read.csv('cv_output/simple_defendant_100.csv')
strict$sd <- sqrt(strict$tau_var)
simple$sd <- sqrt(simple$tau_var)
strict$adj_tau <- strict$tau - 1.96*strict$sd # adjust for the strict rule

## for strict
aupecs_st <- c()
sds_st <- c()
points_st <- c()
for (i in 1:200) {
  b <- bootstrapfunc(data.frame(strict$original_treat, strict$adj_tau, strict$original_outcome))
  aupecs_st <- c(aupecs_st, b$aupec)
  sds_st<- c(sds_st, b$sd)
  points_st <- c(points_st, b$vec)
}

## for simple
aupecs_si <- c()
sds_si <- c()
points_si <- c()
for (i in 1:200) {
  b <- bootstrapfunc(data.frame(simple$original_treat, simple$tau, simple$original_outcome))
  aupecs_si <- c(aupecs_si, b$aupec)
  sds_si<- c(sds_si, b$sd)
  points_si <- c(points_si, b$vec)
}

# turn vec lists into matrices/dataframes
points_st_df <- data.frame(matrix(points_st, ncol = 10000, nrow = 200))
points_st_df <- points_st_df[,seq_len(ncol(points_st_df)) %% 50 == 0]
colnames(points_st_df) <- seq(.005, 1, length.out = 200)
points_si_df <- data.frame(matrix(points_si, ncol = 10000, nrow = 200))
points_si_df <- points_si_df[,seq_len(ncol(points_si_df)) %% 50 == 0]
colnames(points_si_df) <- seq(.005, 1, length.out = 200)

avg_strict <- data.frame(seq(.005, 1, length.out = 200), colMeans(points_st_df))
avg_simple <- data.frame(seq(.005, 1, length.out = 200), colMeans(points_si_df))
colnames(avg_strict) <- c("X", "AvgOutcome")
colnames(avg_simple) <- c("X", "AvgOutcome")
avg_strict$rule <- "strict"
avg_simple$rule <- "simple"
plotting_df <- rbind(avg_strict, avg_simple)

avg_simple <- colMeans(points_si_df)
plotting_df <- data.frame(seq(.005, 1, length.out = 200), avg_strict, avg_simple)

colnames(plotting_df) <- c("X", "strict", "simple")

library(ggplot2)
plt <- ggplot(data = plotting_df, aes(x = X, y = AvgOutcome, color = rule)) +
  theme_minimal() +
  xlab("Proportion of Treated Units") + ylab("Average Outcome") +
  ggtitle("AUPEC Curves: 100 trees, defendant covariate set") +
  geom_smooth() +
  geom_point(alpha = 0.1)
plt
```
