---
title: "geographic-itr"
author: "Jack Deschler"
date: "2022-12-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Functions and setup from prior document
```{r}
# libraries and setup
library(evalITR)
library(dplyr)
library(haven)

# read data
df <- read_dta("~/Desktop/HKS/G1 Fall/Gov 2003/Final Paper/Replication package/Field experiment data and code/TextMessageData.dta")
df <- df[!is.na(df$StatenIsland),] # drop the 1 NA row

# subset to only those with the newform?
df <- df[df$NewForm == 1,]

# Create Treatment column (original does not work for some reason)
df$Treatment <- df$consequences + df$planmaking + df$combination

# Flip FTA because a success is actually appearing
df$success <- 1 - df$FTA


control <- df[df$Treatment == 0,]
treated_overall <- df[df$Treatment == 1,]
cons <- df[df$consequences == 1,]
plan <- df[df$planmaking == 1,]
combo <- df[df$combination == 1,]

pape_matrix <- function(d, itr_cols = c('itr_plan', 'itr_cons', 'itr_combo')) {
  itr_treat <- as.numeric(d$itr_plan + d$itr_cons + d$itr_combo > 0)
  appeared <- 1 - d$FTA

  names <- list("Any Text", "Planmaking", "Consequences", "Combination")
  orig <- data.frame(d$Treatment, d$planmaking, d$consequences, d$combination)
  itr <- data.frame(itr_treat, d[itr_cols[1]], d[itr_cols[2]], d[itr_cols[3]])
  pape_mat <- matrix(nrow = 4, ncol = 4, c(names, names))
  sd_mat <- matrix(nrow = 4, ncol = 4, c(names, names))
  for (r in 1:length(names)) {
    for (c in 1:length(names)) {
      p = PAPE(orig[,r], itr[,c], appeared, centered = FALSE)
      pape_mat[r,c] <- p$pape
      sd_mat[r,c] <- p$sd
    }
  }
  rownames(pape_mat) <- names
  colnames(pape_mat) <- names
  rownames(sd_mat) <- names
  colnames(sd_mat) <- names
  return(tibble(pape = pape_mat, sd = sd_mat))
}

pape_matrix_to_metric <- function(papes, weights) {
  d <- dim(papes)[1]
  papes <- matrix(as.numeric(papes), nrow = d, ncol = d)
  if(!is.matrix(weights)) {
    weights <- diag(weights)
  }
  return(sum(papes * weights))
}
```

# Geographic ITRs
```{r}
# set up treatment conditions:
conds <- 3 # start with treating everyone, see how fast it goes
           # set conds to 4 to include control as an option
max <- conds ^ 5
StatenIsland <- c()
Bronx <- c()
Brooklyn <- c()
Manhattan <- c()
Queens <- c()

for (i in 1:max) {
  StatenIsland <- c(StatenIsland, i %% conds)
  Bronx <- c(Bronx, (i %/% conds) %% conds)
  Brooklyn <- c(Brooklyn, (i %/% conds^2) %% conds)
  Manhattan <- c(Manhattan, (i %/% conds^3) %% conds)
  Queens <- c(Queens, (i %/% conds^4) %% conds)
}

geos <- data.frame(StatenIsland, Bronx, Brooklyn, Manhattan, Queens)
geos[geos == 0] <- 'plan'
geos[geos == 1] <- 'cons'
geos[geos == 2] <- 'combo'
geos[geos == 3] <- 'control'

get_pape_matrix <- function(row) {
  tmp <- df # keep main copy pure
  tmp$itr_plan <- 0
  tmp$itr_cons <- 0
  tmp$itr_combo <- 0
  tmp$itr_control <- 0
  boroughs <- c("StatenIsland", "Bronx", "Brooklyn", "Manhattan", "Queens")
  for (b in boroughs) {
    text_plan <- paste("itr_", as.character(row[b]), sep = '')
    tmp[text_plan][tmp[b] == 1] <- 1
  }
  return(pape_matrix(tmp))
}

get_pape_metric <- function(x) {
  return(pape_matrix_to_metric(get_pape_matrix(x)$pape, weights = c(.25, .25, .25, .25)))
}

get_pape_sd <- function(x) {
  sd_mat <- get_pape_matrix(x)$sd
  sd_mat <- matrix(as.numeric(sd_mat), nrow = d, ncol = d)
  var_mat <- sd_mat * sd_mat
  w <- .25 ^ 2
  var_overall <- pape_matrix_to_metric(var_mat, weights = c(w,w,w,w))
  return(sqrt(var_overall))
}

geos$pape_metric <- apply(geos, 1, get_pape_metric)
geos$pape_metric_sd <- apply(geos, 1, get_pape_sd)
```

# Evaluation
```{r}
geo_three_way <- read.csv('geo_itr_papes.csv')
geo_four_way <- read.csv('geo_itr_papes_withcontrol.csv')
```